### ISSUE TITLE
No contract addresses

### ISSUE THREAD

**Issue by potrepka** [manifoldxyz/creator-core-solidity#10]
There are no contract addresses to show where the Manifold Creator contract implementations are deployed.

**Comment by wwhchung** [comment]
Do you mean the contract addresses of what the ones created on Manifold Studio point to?

**Comment by potrepka** [comment]
> Do you mean the contract addresses of what the ones created on Manifold Studio point to?

Yes. These contracts are deployed on Ethereum mainnet, right?

**Comment by wwhchung** [comment]
Yes:
ERC1155: 0x6bf5ed59dE0E19999d264746843FF931c0133090
ERC721: 0x2d3fC875de7Fe7Da43AD0afa0E7023c9B91D06b1

Goerli:
ERC1155: 0xb08Aa31Cc2B8C0582bE42D38Bb643292e0A4b9EB
ERC721: 0xEB067AfFd7390f833eec76BF0C523Cf074a7713C
