### ISSUE TITLE
Most Gas Efficient Way to Deploy Programmatically (Max Size Exceeded)

### ISSUE THREAD

**Issue by sandeepsuresh2020** [manifoldxyz/creator-core-solidity#12]
Hi, noticing that when I try creating a contract that is an `ERC1155Creator`, I run into the problem of `max size exceeded`. This was the source code below. I tried use an optimizer with less runs and that seems to work but wondering if I'm missing something:
```
pragma solidity ^0.8.0;

import "@manifoldxyz/creator-core-solidity/contracts/ERC1155Creator.sol";

contract TestContract is ERC1155Creator  {
    constructor() ERC1155Creator("TestContract", "MC") {
    }
}

```

If I wanted to programmatically create many contracts like this, how would you suggest doing so? I'm wondering if importing directly from NPM package is more costly than importing the files myself. The context here is I'm trying to create a similar UX to manifold studios, but wondering the best way to go about it.

**Comment by wwhchung** [comment]
You're not missing anything.  If you extend the contract, it will be above the bytecode size limit unless you reduce the optimizer runs.

If you want to deploy many instances, I suggest you use the diamond proxy pattern and deploy proxy contracts which reference an implementation contract deployment:
https://github.com/manifoldxyz/creator-core-solidity/blob/main/contracts/ERC1155CreatorImplementation.sol

You can also deploy proxy contracts referencing the Manifold deployed implementations for ERC1155.
Goerli: 0xb08Aa31Cc2B8C0582bE42D38Bb643292e0A4b9EB
Mainnet: 0x6bf5ed59dE0E19999d264746843FF931c0133090

**Comment by sandeepsuresh2020** [comment]
Hey @wwhchung thanks for the quick response really appreciate that! Not too familiar with the diamond pattern specifically, but is the idea that I create a simple contract that doesn't extend anything but then delegates all calls to the ERC1155CreatorImplementation?

I'm a bit confused because looking at a contract that has been deployed on goerli through manifold studio (https://goerli.etherscan.io//address/0xbd84762ce53071795e54c6de3bf7997a7a57c8f0#code), it looks like the contract that is created is still extending the `ERC1155CreatorCore` and that class is the one that specifies the address of the implementation contract. So would the idea be: instead I create a contract that is a proxy and has similar logic to the ERC1155CreatorCore and delegates all calls to the Implementation contract, effectively bypassing the ERC1155CreatorCore?

**Comment by wwhchung** [comment]
It doesn’t extend creator core. It extends a contract called ERC1155Creator which proxies to the implementation address. You can follow the same pattern (the diamond pattern).

**Comment by sandeepsuresh2020** [comment]
Sorry yah I misspoke I meant to say that it extends `ERC1155Creator`. Am I not following the same pattern above by extending `ERC1155Creator` in the original code snippet I sent?

**Comment by wwhchung** [comment]
No. Look at the code deployed. It’s a different contract with the same name.

**Comment by sandeepsuresh2020** [comment]
I see so the `ERC1155Creator` that is extended in the goerli deployment is not the same `ERC1155Creator` that is in the manifold package? So the suggestion is that I can create my own contract that extends a version of ERC1155Creator that I create that delegates all the calls to the implementation contract manifold already deployed? Apologies if these are uninformed questions still just getting started and a lot to learn so appreciate you breaking this down for me.

**Comment by wwhchung** [comment]
Yes, that's correct

**Comment by sandeepsuresh2020** [comment]
Great thank you for all the help @wwhchung 💯
