### ISSUE TITLE
Creator contracts contain dead code in their runtime bytecode, can be optimized

### ISSUE THREAD

**Issue by sifislag** [manifoldxyz/creator-core-solidity#15]
Hi,
We (Dedaub) recently reported a [solc issue](https://github.com/ethereum/solidity/issues/13680) which results in the inclusion of functions that are used only during contract construction to the runtime bytecode. We ran some experiments at scale to assess the bug's impact of and found thousands of deployments of contracts extending your Creator proxies.

You can read more details in our [medium post](https://medium.com/@sifislag/2a9c13d0b98e?source=friends_link&sk=82245f0b858a6853ccbecf047c16c7dc). Bottom line is 500 of the 800 bytes of the deployed bytecode of your contracts is dead code, increasing your deployment costs. Alternatively, the `--via-ir` pipeline is not affected by that bug and produces a bytecode of 258 bytes.

**Comment by wwhchung** [comment]
Great point!  Thanks for pointing this out.  We'll be looking into fixing this and addressing.

**Comment by wwhchung** [comment]
Fix is in progress.  Once it's out, will tweet and tag you guys as well.  Great find on the compiler bug!

**Comment by wwhchung** [comment]
In test. Looking good
https://goerli.etherscan.io/address/0xbcff5bb8657d46179928bfc7cc2bc343be4852fe

**Comment by sifislag** [comment]
Great to hear! Glad to help!

**Comment by wwhchung** [comment]
Updated!
