### ISSUE TITLE
Typo on documentation

### ISSUE THREAD

**Issue by daniniguez** [manifoldxyz/creator-core-solidity#2]
This might not be at all the place to let you guys now about this but didn't find any other place where to share this. Sorry about it!

Found a typo over at the manifold studio docs:

https://docs.manifold.xyz/deploying-contracts/contract-customization

Where it says "but we aware" I'm sensing maybe it's missing ^are:

![image](https://user-images.githubusercontent.com/48453683/151691594-6ed1c89d-10b3-427d-b2a8-7080b9dae9f0.png)

*First paragraph, second line, around character 54*

**Comment by wwhchung** [comment]
Fixed, thanks!
