### ISSUE TITLE
Setbasetokenuri not working

### ISSUE THREAD

**Issue by bgibers** [manifoldxyz/creator-core-solidity#20]
[See issue in forum. ](https://forum.manifold.xyz/t/setbasetokenuri-does-not-work/4371). Writing to the proxy function goes through, but the base url never changes. Also on a separate contract, setTokenUri is not working, and is giving the error "invalid tokenId" when I am using a correct token Id.

**Comment by wwhchung** [comment]
Not a bug. Base uri is only used if you mint base without a uri string.
