### ISSUE TITLE
Error - Initializable: contract is already initialized

### ISSUE THREAD

**Issue by NemboKid** [manifoldxyz/creator-core-solidity#21]
I first used your contract as a submodule and got this error in my hardhat unit tests:
```
    const ERC1155Impl: ContractFactory = await ethers.getContractFactory(
      "ERC1155CreatorImplementation"
    );
    const implementationContract = await ERC1155Impl.deploy();
    await implementationContract.deployTransaction.wait();
    await implementationContract.initialize("Name", "Symbol"); // error: Initializable: contract is already initialized
```
Then just to verify the error, I cloned this repo, deployed ERC1155CreatorImplementation to Goerli and verified the contract using Foundry. I then went to etherscan and tried to initialize the contract, but then I got this error (which I also could double and triple check with Tenderly).

`forge create --rpc-url https://eth-goerli.g.alchemy.com/v2/rpc_key --private-key private_key --verify contracts/ERC1155CreatorImplementation.sol:ERC1155CreatorImplementation --etherscan-api-key api_key`

In `foundry.toml` I added:
```
solc = "0.8.16"
optimizer = true
optimizer_runs = 1
```

If I had to guess, it has to do with OpenZeppelin deprecating `isContract()` which now instead should be like `address(this).code.length == 0`, and perhaps there's a mismatch between versions? 

Please let me know if you can reproduce.

**Comment by NemboKid** [comment]
The implementation contract is inheriting `ERC1155Upgradeable` which calls `_disableInitializers()`. So the implementation is initialized on deployment and not like before where you had to do it yourself.

**Comment by wwhchung** [comment]
You’re not supposed to initialize the implementation as it’s supposed to act as an implementation for a proxy deployment.
