### ISSUE TITLE
max code size exceeded

### ISSUE THREAD

**Issue by SweetmanTech** [manifoldxyz/creator-core-solidity#3]
I'm trying to follow the `README` example and I'm getting a deployment error:

```
ProviderError: max code size exceeded
```
<img width="1439" alt="Screen Shot 2022-05-07 at 5 29 21 PM" src="https://user-images.githubusercontent.com/23249402/167270753-8c96b267-cb9d-41a4-9fba-9b1e777dce54.png">

### Here's my contract:
```
pragma solidity ^0.8.0;

import "@manifoldxyz/creator-core-solidity/contracts/ERC721Creator.sol";

contract Greeter is ERC721Creator {
    constructor() ERC721Creator("MyContract", "MC") {}
}

```

### deploy script
```
async function main() {
  const Greeter = await hre.ethers.getContractFactory("Greeter");
  const greeter = await Greeter.deploy();

  await greeter.deployed();

  console.log("Greeter deployed to:", greeter.address);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

Can you help?

**Comment by SweetmanTech** [comment]
I've also been communicating with [Richerd.eth](https://twitter.com/richerd) in Twitter dms 📬 

He recommended I try deploying from [Ethereum Remix IDE](https://remix.ethereum.org/).

Here's my attempt to deploy `ERC721Creator.sol`:
![MAX_CODE_SIZE](https://user-images.githubusercontent.com/23249402/167298159-31df979f-c169-46df-8e59-b5f394408c94.gif)

As well as the failed tx hash: https://rinkeby.etherscan.io/tx/0xfbd3f53208c9b7fec9228567e0e7fe838e0076f134f33be8a823c693cd854a2e

**Comment by ljcutts** [comment]
It looks like you are trying to deploy the contract you are inheriting, which is "ERC721Creator". What you should really be deploying is "MyContract"

**Comment by wwhchung** [comment]
Try the optimizer with fewer runs (e.g. 150) when compiling.  Sorry for the delayed response.
